server:
  port: 8001

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stockDB
    rest:
      basePath: /datarest

api:
  priceServiceConfig:
    priceService: http://localhost:8003
    getPricesByFigies: /prices
  stockConfig:
    stockService: http://localhost:8002
    getStocksByTickers: /stocks/getByTickers

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file:
    name: logs/UserService.log

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

data:
  rest:
    basePath: /datarest
