server:
  port: 8001

spring:
  application:
    name: user-service
  cloud:
    loadbalancer:
      enabled: true
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: 27017
      database: stockDB
    rest:
      basePath: /datarest

api:
  priceServiceConfig:
    priceService: ${API_PRICE_SERVICE_CONFIG_PRICE_SERVICE:http://localhost:8003}
    getPricesByFigies: /prices
  stockConfig:
    stockService: ${API_STOCK_CONFIG_STOCK_SERVICE:http://localhost:8002}
    getStocksByTickers: /stocks/getByTickers

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file:
    name: logs/UserService.log

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: user-service

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000  # 24 hours in milliseconds

data:
  rest:
    basePath: /datarest
