server:
  port: 8002

spring:
  application:
    name: stock-service
  cloud:
    loadbalancer:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: stock-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

api:
  tinkoffConfig:
    tinkoffService: http://tinkoff-stock-service:8004
    getStocksByTickers: /stocks/getStocksByTickers
    getPrices: /prices

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    root : INFO
    org.springframework.cloud.gateway: DEBUG
  file:
    name: logs/StockService.log
