server:
  port: 8004

spring:
  application:
    name: tinkoff-stock-service
  cloud:
    loadbalancer:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: tinkoff-stock-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

tbank:
  token: ${TBANK_TOKEN}

