server:
  port: 8003

spring:
  application:
    name: price-service
  cloud:
    loadbalancer:
      enabled: true
  data:
    redis:
      host: redis
      port: 6379
      database: 0

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file:
    name: logs/PriceService.log

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: false
    hostname: price-service
    status-page-url: http://localhost:8003/actuator/info
    health-check-url: http://localhost:8003/actuator/health
    home-page-url: http://localhost:8003/
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    app:
      name: ${spring.application.name}
      description: Price Service for Financial System

springdoc:
  api-docs:
    path: /api-docs

price:
  monitoring:
    update-interval: ${PRICE_UPDATE_INTERVAL:30000}  # Интервал обновления цен в миллисекундах (по умолчанию 30 секунд)
